export interface IPlayerStats {
	partitionKey: string
	rowKey: string
	playerId: number
	playerName: string
	teamName: string
	position: string
    gamesPlayed: string
	totalPoints: number
	averagePoints: number
	maxPoints: number
	minPoints: number
	totalMinutes: number
	averageMinutes: number
	maxMinutes: number
	minMinutes: number
	totalFieldGoalsMade: number
	averageFieldGoalsMade: number
	maxFieldGoalsMade: number
	minFieldGoalsMade: number
	totalFieldGoalAttempts: number
	averageFieldGoalAttempts: number
	maxFieldGoalAttempts: number
	minFieldGoalAttempts: number
	fieldGoalPercentage: number
	maxFieldGoalPercentage: number
	minFieldGoalPercentage: number
	totalFreeThrowsMade: number
	averageFreeThrowsMade: number
	maxFreeThrowsMade: number
	minFreeThrowsMade: number
	totalFreeThrowsAttempted: number
	averageFreeThrowsAttempted: number
	maxFreeThrowsAttempted: number
	minFreeThrowsAttempted: number
	freeThrowPercentage: number
	totalThreePointersMade: number
	averageThreePointersMade: number
	maxThreePointersMade: number
	minThreePointersMade: number
	totalThreePointersAttempted: number
	averageThreePointersAttempted: number
	maxThreePointersAttempted: number
	minThreePointersAttempted: number
	threePointerPercentage: number
	totalOffensiveRebounds: number
	averageOffensiveRebounds: number
	maxOffensiveRebounds: number
	minOffensiveRebounds: number
	totalDefensiveRebounds: number
	averageDefensiveRebounds: number
	maxDefensiveRebounds: number
	minDefensiveRebounds: number
	averageRebounds: number
	totalRebounds: number
	totalAssists: number
	averageAssists: number
	maxAssists: number
	minAssists: number
	totalFouls: number
	averageFouls: number
	maxFouls: number
	minFouls: number
	totalSteals: number
	averageSteals: number
	maxSteals: number
	minSteals: number
	totalTurnovers: number
	averageTurnovers: number
	maxTurnovers: number
	minTurnovers: number
	totalBlocks: number
	averageBlocks: number
	maxBlocks: number
	minBlocks: number
	seasonPlusMinus: number
	averagePlusMinus: number
	maxPlusMinus: number
	minPlusMinus: number
	timestamp: string
	eTag: string
}